### ISSUE TITLE
The search bar is not working on the user's website

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/core-web-vitals-pagespeed-booster#92] opened 2023-06-13 13:07 UTC
The search bar is not working on the user's website and appears bank after activating the plugin

Ref ticket: https://magazine3.in/conversation/150052?folder_id=27

**Comment by akshaywali** [comment] 2023-08-16 08:05
Upon inspection it is found that homepage search button has an onclick attributed which takes it to other page, while on other pages the attribute doesn't exists . Rest our plugin does not add any onclick attribute to any element  so this issue is not caused by our plugin. 
Some theme or other plugin might be adding the attribute causing the issue

![home-issue](https://github.com/ahmedkaludi/core-web-vitals-pagespeed-booster/assets/36995680/6be4963a-347d-43c6-9347-63d0f2f0281d)

**Homepage search button**

![service-no-issue](https://github.com/ahmedkaludi/core-web-vitals-pagespeed-booster/assets/36995680/a0dfd967-a375-401b-915a-2806cd83665d)

**search button on other pages**

**Comment by akshaywali** [comment] 2023-08-17 07:52
Closing ticket  as the  issue is not caused by our plugin. Still if anybody feels that issue is somehow related to CWVPB they can create a new ticket

**Closed by akshaywali** 2023-08-17 07:52 UTC
Labels: bug, ready for review, high
